from .animals import RiverDolphin
from .habitats import Aquatic
from .habitats import Freshwater
from .habitats import Saltwater
from .habitats import Terrestrial
from .movements import Flying
from .movements import Swimming
from .movements import Walking
from .animal import Animal